apiVersion: v1
kind: Service
metadata:
  name: agent-pool
spec:
  ports:
    - protocol: TCP
      port: 6443
      targetPort: 6443
---
apiVersion: v1
kind: Endpoints
metadata:
  # the name here should match the name of the Service
  name: agent-pool
subsets:
  - addresses:
      - ip: 192.168.20.21
    ports:
      - port: 6443