apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-robot
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
  annotations:
    kubernetes.io/service-account.name: jenkins-robot
type: kubernetes.io/service-account-token