---
apiVersion: v1
kind: Pod
metadata:
  name: mc-with-host-path
spec: 
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
      - mountPath: /share
        name: my-host-path-volume
    - name: busybox-container
      image: busybox:latest
      command: ["/bin/sh"]
      args: ["-c", "while true; do sleep 30; done;"] # Prevents busybox from exiting after completion
      volumeMounts:
      - mountPath: /share
        name: my-host-path-volume
  volumes:
  - name: my-host-path-volume
    hostPath:
      # directory location on host
      path: /tmp
      # this field is optional
      type: Directory