---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-mc
spec: 
  containers:
    - name: nginx-container
      image: nginx:latest
    - name: busybox-container
      image: busybox:latest
      tty: true