---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
spec:
  containers:
    - name: nginx-configmap-select
      image: nginx:latest
      env:
        - name: stack #Any other name works here.
          valueFrom:
            configMapKeyRef:
              name: genericmap
              key: stack
  nodeSelector:
    kubernetes.io/hostname: kind-worker
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
spec:
  containers:
    - name: nginx-configmap-all
      image: nginx:latest # will not work if on same port as port 80 is in use
      envFrom:
        - configMapRef:
            name: genericmap
  nodeSelector:
    kubernetes.io/hostname: kind-worker2
