apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath-var
  labels:
    type: hostpath
    env: prod 
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostpath-var
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
       type: hostpath
       env: prod  