# https://docs.docker.com/engine/install/ubuntu/
---
- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - python3-pip
      - python3-setuptools
      - software-properties-common
      - virtualenv
      - net-tools
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# $(lsb_release -cs) = focal 
- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ lsb_release }} stable
    state: present

- name: Update apt and install docker-ce
  apt:
    pkg:
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - docker-compose
    state: latest
    update_cache: true
  register: docker_ce_ouput
- debug: var=docker_ce_ouput

- name: Add user to Docker and cluster groups, they will need to logout and in again # did not work
  user:
    name: '{{ lookup("env", "USER") }}'
    state: present
    groups:
      - docker
    append: true

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Pull default Docker image
  community.docker.docker_image:
    name: "{{ default_container_image }}"
    source: pull

# - name: Create default containers
#   community.docker.docker_container:
#     name: "{{ default_container_name }}{{ item }}"
#     image: "{{ default_container_image }}"
#     command: "{{ default_container_command }}"
#     state: absent
#   with_sequence: count={{ container_count }}
