apiVersion: v1
kind: Service
metadata:
  name: nginx-rolling-1-svc
spec:
  selector:
    app: nginx
    environment: test
  type: NodePort
  # type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80